# Generated by Django 4.2.7 on 2023-12-17 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_title_product_name'),
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserecord',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='productId',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
